### ISSUE TITLE
Make force date available for receipts after purchase order confirmation

### ISSUE THREAD

**Issue by treviser** [twanda/vertical-agriculture#10]
I'm not sure if this is related to our agriculture project, maybe it is an issue in the bought module?

However, we have to make sure that all weight corrections movements do use the force date, or the effective dates of the original receipts and deliveries. 

The image shows the weight correction transfer where it is correct.

![2021-04-05_10-22](https://user-images.githubusercontent.com/1814941/113739670-4ba79480-9700-11eb-890f-a38054188759.png)

**Comment by candidroot** [comment]
make force_date field readonly in done state.  copy force_date while doing catch weight
