### ISSUE TITLE
[new feature]:agriculture: Import of GeoJson and GPX data for plantations, Polygonize Multilines  and close the polygons (start point = end point) if necessary

### ISSUE THREAD

**Issue by treviser** [twanda/vertical-agriculture#11]
We should have the possibility to import geojson data to plantations. At the moment we can draw a polygon on the map and the geo data are then saved.
We should have the possibility to import it on the plantation form and in a second step, to import it by csv/Excel import.
I have found the following documents relating to this matter:

https://github.com/dek-odoo/odoo-import-scripts/blob/master/gis_geojson_odoo_import/import_geojson_data.py

https://github.com/OCA/geospatial/issues/214

Please find attached a sample geojson-file for a plantation:
[Piste_KES365.zip](https://github.com/twanda/vertical-agriculture/files/6266099/Piste_KES365.zip)

Originally, I have received the plantation geodata as gpx files and have converted them using https://mapbox.github.io/togeojson/
If you know an easy/simple way to directly import gpx data, that would be very nice, else I ask the customer to export his GIS data as geojson files directly.

**Comment by treviser** [comment]
Today I had a conversation with my customer, there are 2 import points for my customer:
- we need to have the possibility to import gpx-files directly.
- we can not be sure that the multiline tracks do close perfectly, so when creating the polygons, we should find a solution to close them automatically using shapely or other algorithms. The polygons must not be extremely accurate.

Background: for my customer it is easier to invest more in intelligent software than to train and control the people on site to provide perfect data.

**Comment by treviser** [comment]
@dastcaboz Dani: please test and close the issue if successful.

**Comment by dastcaboz** [comment]
<img width="2121" alt="Bildschirmfoto 2021-09-17 um 11 04 20" src="https://user-images.githubusercontent.com/90847414/133757146-192168ab-e4c8-4b08-a911-3a3756cbe77b.png">
 I still get the same bug on MAC OS 11.5.2, Firefox 92.0

**Comment by dastcaboz** [comment]
<img width="2626" alt="Bildschirmfoto 2021-09-17 um 11 08 45" src="https://user-images.githubusercontent.com/90847414/133757180-d9317e18-0b4d-47fb-8a50-02d96e91e86d.png">
Same issue in Chrome Version 93.0.4577.82 und MacOS 11.5.2

**Comment by treviser** [comment]
@dastcaboz Please check on test-caboz and close if it works as expected.

**Comment by dastcaboz** [comment]
<img width="1440" alt="211018_upload_gpx_on_macOS" src="https://user-images.githubusercontent.com/90847414/137729459-4ac77090-3410-4736-80e8-25d9803505dc.png">

Still the same issue. Please resolve!

**Comment by candidroot** [comment]
@treviser 
if possible then can you please make small video on this issue,
so i can easily identify the issue,
thanks

**Comment by dastcaboz** [comment]
https://user-images.githubusercontent.com/90847414/139662784-0598ef29-9602-4eee-b4e8-bf07c03ab838.mov

**Comment by candidroot** [comment]
@treviser 
For this Warning issue i committed code, So please take latest pull on both server then check it,
is there any update please let me know,
thanks
