### ISSUE TITLE
[Error]Weight Correction on pickings

### ISSUE THREAD

**Issue by treviser** [twanda/vertical-agriculture#16]
![2021-04-13_18-42](https://user-images.githubusercontent.com/1814941/115998740-fcf76700-a5e8-11eb-8747-dca1ba5f3bfc.png)

**Comment by candidroot** [comment]
file:///home/sid/Downloads/Magasin%20Carri%C3%A8re_%20Pick%20-%20Odoo.jpg

**Comment by candidroot** [comment]
@treviser 
![Magasin Carrière_ Pick - Odoo](https://user-images.githubusercontent.com/39722234/116193784-832cbe00-a74d-11eb-82c7-b1d64d96f259.jpg)

**Comment by treviser** [comment]
Sorry for the noise and thanks!
