### ISSUE TITLE
Delete or archive farmers together with their plantations

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#23]
Every year we stop working with certain farmers. To make this process as easy as possible it should be possible to change the status of the farmer and his plantations in one step.

**Comment by treviser** [comment]
Please assign the proper label from your point of view.

**Comment by dastcaboz** [comment]
What do mean by label?

**Comment by dastcaboz** [comment]
<img width="2121" alt="Bildschirmfoto 2021-09-17 um 11 04 20" src="https://user-images.githubusercontent.com/90847414/133756227-3a4d99f2-d679-47c3-ba0a-42b77cd8380c.png">
I still get the same bug on MAC OS 11.5.2, Firefox 92.0

**Comment by dastcaboz** [comment]
<img width="2626" alt="Bildschirmfoto 2021-09-17 um 11 08 45" src="https://user-images.githubusercontent.com/90847414/133756847-e2bcdb06-e8aa-4d64-9e40-4541c39d6b3a.png">
Same issue in Chrome Version 93.0.4577.82 und MacOS 11.5.2

**Comment by treviser** [comment]
@dastcaboz Please check on test-caboz and close if it works as expected.

**Comment by dastcaboz** [comment]
Great! Thank you.
