### ISSUE TITLE
Plantation: Automated calculation of surface and geograhical centerpoint based on geodata

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#24]
Based on uploaded .gpx file odoo should calculate for every plantation:

1. surface in ha with 4 digits precision
2. geographical center point with x / y coordinates

Both informations must get displayed in "Details" tap of the plantation in seperate fields.

The geograhical centerpoint should also get visualized on the map as a point.

**Comment by candidroot** [comment]
@treviser 
 I have update code please verify the calculation of area and center point are correct or not

**Comment by treviser** [comment]
@dastcaboz can you please check?

**Comment by danielstaehli** [comment]
On the testserver I do not see any informations related to the surface calculation or the centrepoint. How can I verify this?

**Comment by candidroot** [comment]
@treviser 
Can you please take latest pull on test server and upgrade module,
then after you can see as below images 
![screenshot-localhost_8069-2021 11 01-14_55_48](https://user-images.githubusercontent.com/39722234/139650785-45f6e2fe-ffe3-4dd6-9c38-1a586c43d166.png)

**Comment by treviser** [comment]
@dastcaboz Please check

**Comment by dastcaboz** [comment]
It is visible on life server but not test server.
![Issue #24](https://user-images.githubusercontent.com/90847414/139664605-d93e99fa-fe80-48d3-abfb-3c08082385f5.jpg)

**Comment by treviser** [comment]
@dastcaboz now also on test server, please check.

![image](https://user-images.githubusercontent.com/1814941/141160270-7612fda1-dafa-4404-b6d1-832bb144e1f3.png)

**Comment by dastcaboz** [comment]
Yes I can see ist is there. But the surface in ha and the position of the centerpoint of the plantation uploaded is not calculated.
![surface_centerponit_callculation_01](https://user-images.githubusercontent.com/90847414/141162093-0a4348c7-2ee1-491e-af8e-b504c593c584.jpg)
![surface_centerponit_callculation_01 jpg](https://user-images.githubusercontent.com/90847414/141162107-84ae5890-9dcf-4647-b2b1-53c7680989c5.jpg)

**Comment by treviser** [comment]
@candidroot Surface and center point must be calculated from the gpx data.

**Comment by candidroot** [comment]
@treviser 
Please check attached video 
I already did test on test server "https://test-caboz.twanda-hosting.ch/" In that server point calculated from the GPX data

Still not working on your side then,  please make video and send me,
if possible then please also send me GPX file which you uploaded.

https://user-images.githubusercontent.com/39722234/141731946-87007820-ac4d-437e-afe8-fd82a34a6240.mp4
