### ISSUE TITLE
Adding a partner relation "Final Customer" to the quotation/sales order

### ISSUE THREAD

**Issue by treviser** [twanda/vertical-agriculture#28]
The sales chain after the selling to an exporter at the harbor is not transparent to Caboz and might be very complex. Multiple actors might be involved until the final customer has consumed the sale from Caboz. Nevertheless, the final customer must be able to trace back its deliveries to the farmers on the customer portal.
But Caboz knows the final customer at the time of posting a quotation/sales order to an exporter.

So the "legal" customer of Caboz is an exporter at the harbor, but the "economic" customer of Caboz is a manufacturer/brand which wants to track its produce from Caboz back to the farmer and its plantations.

@dastcaboz Please  provide a french translation for the term "Final Customer".

**Comment by dastcaboz** [comment]
English: "Final Customer", French: "Client final"

**Comment by candidroot** [comment]
@treviser 
In this task do we need to just add partner relation "Final customer" field in quotation/sales order?

is it manually process to fill this field's value on quotation ?

**Comment by treviser** [comment]
@candidroot 
> @treviser In this task do we need to just add partner relation "Final customer" field in quotation/sales order?
> 
> is it manually process to fill this field's value on quotation ?

Yes and yes. The field shall not be mandatory.

**Comment by treviser** [comment]
@dastcaboz Please check on test-caboz and close if it works as expected.

**Comment by dastcaboz** [comment]
This is great. But could you move the field "Final Customer" below the field "Costumer"? Thank you.
