### ISSUE TITLE
Stock move Vendor Location --> Stock

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#29]
When registering the Transfers from _Farmer Vendor Location_ to _Stock_ in the _Purchase Order_ the user must select a _Vendor Location_. Odoo should not save a transfer if the generic _Vendor Loaction_ (Partner Locations/Vendors) is selected. Instead a warning should appear.

<img width="1962" alt="Bildschirmfoto 2021-09-24 um 10 03 24" src="https://user-images.githubusercontent.com/90847414/134641293-75123843-6fe1-4b5e-a1cc-5ecd7c432a7c.png">

<img width="1962" alt="Bildschirmfoto 2021-09-24 um 10 04 38" src="https://user-images.githubusercontent.com/90847414/134641302-a2232630-2a42-44f0-b088-103d9ab257d6.png">

**Comment by treviser** [comment]
@dastcaboz Please check on test-caboz and close if it works as expected.

**Comment by dastcaboz** [comment]
Perect. Thank you!
