### ISSUE TITLE
Document template for Purchase and Sales orders look weird

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#30]
Odoo does not generate purchase or sales orders or invoices corresponding to the chosen template.
<img width="977" alt="Bildschirmfoto 2021-09-24 um 10 15 59" src="https://user-images.githubusercontent.com/90847414/134641825-46d6e0fb-59c1-43bd-9995-43250746bec2.png">
[Preview External Report-2.pdf](https://github.com/twanda/vertical-agriculture/files/7224159/Preview.External.Report-2.pdf)

**Comment by treviser** [comment]
This is a report.url issue (system setup), I will have to take care of it.

**Comment by treviser** [comment]
@dastcaboz  should work now properly, please check and close if correct.

**Comment by dastcaboz** [comment]
The test version still generates an incorrect layout of the sales bill. I cannot test it in the life version for the moment as there are no bills generated yet.
[document.pdf](https://github.com/twanda/vertical-agriculture/files/7451866/document.pdf)

**Comment by dastcaboz** [comment]
Still the same issue in the test version.

**Comment by dastcaboz** [comment]
Same issue in new life version.

**Comment by treviser** [comment]
@dastcaboz 
The corresponding system parameter report.url got lost, probably during the last update, that is really strange and annoying :-(

**Comment by treviser** [comment]
@dastcaboz Now it is back again, please check.

![image](https://user-images.githubusercontent.com/1814941/141159960-915f4c18-9516-4b50-942f-8bd2349e40cf.png)

**Comment by treviser** [comment]
@candidroot  Do you know about something like report.url.freeze :-)    ?????
Same as web.base.url.freeze?

**Comment by dastcaboz** [comment]
Great thank you!
