### ISSUE TITLE
Transfers from a Farmer Loaction should be displayed in farmer view

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#31]
Although there is no direct purchase with a farmer (only with the purchase agent) it is important that we can view and analyse in reports how much a farmer has delivered. This would correspond to his stock inventory for a given period.

Transfer of 250 kg from KES/029 to Stock:
<img width="1177" alt="Bildschirmfoto 2021-09-24 um 10 35 55" src="https://user-images.githubusercontent.com/90847414/134646526-80105e74-ea50-4ef9-b638-96143ee574b5.png">

This information is not shown in these views:
<img width="1643" alt="Bildschirmfoto 2021-09-24 um 10 39 50" src="https://user-images.githubusercontent.com/90847414/134646603-ea6f833f-cd6c-40bf-a1c8-8b23ccb1b528.png">
<img width="1562" alt="Bildschirmfoto 2021-09-24 um 10 41 47" src="https://user-images.githubusercontent.com/90847414/134646622-8471aa57-10eb-4661-b207-f13b6a5158d0.png">

We can only access these informations in a too complicated way:
<img width="1586" alt="Bildschirmfoto 2021-09-24 um 10 43 01" src="https://user-images.githubusercontent.com/90847414/134646718-0503df0f-b8b9-4e44-8799-d06dc3df95ef.png">
<img width="2559" alt="Bildschirmfoto 2021-09-24 um 10 44 02" src="https://user-images.githubusercontent.com/90847414/134646750-ce98c92e-460d-49ee-90fa-8a1b3fcefaf9.png">
<img width="2559" alt="Bildschirmfoto 2021-09-24 um 10 46 24" src="https://user-images.githubusercontent.com/90847414/134646763-3132f9ed-0016-419b-a04c-7172a46a85c0.png">

**Comment by treviser** [comment]
@candidroot A smart button relating to the stock moves of the corresponding vendor location should do the trick I believe.

**Comment by treviser** [comment]
@dastcaboz Please check on test-caboz and close if it works as expected.

**Comment by dastcaboz** [comment]
I cannot see the new smart button.
<img width="1440" alt="Bildschirmfoto 2021-09-30 um 10 52 24" src="https://user-images.githubusercontent.com/90847414/135420605-a1ad48f1-36ba-4eeb-ac41-3ad61102ae36.png">

**Comment by treviser** [comment]
@dastcaboz The smart button "Current Stock" is now directly available at the farmer form view without the detour over the assigned vendor location
![farmercurrentstock](https://user-images.githubusercontent.com/1814941/135439111-e2cc3c10-303b-4ad1-84d7-3627d7fc0a96.png)
.

**Comment by dastcaboz** [comment]
OK. Sorry for the misunderstanding. Could the current stock be displayed in the smart button just as in the others?

**Comment by treviser** [comment]
@dastcaboz 

> OK. Sorry for the misunderstanding. Could the current stock be displayed in the smart button just as in the others?

Please be more specific, I do not understand.

**Comment by dastcaboz** [comment]
Like this:
<img width="1440" alt="Bildschirmfoto 2021-09-30 um 15 26 12" src="https://user-images.githubusercontent.com/90847414/135464113-edf339de-141e-474c-9e91-5c3a4e35dec0.png">

**Comment by dastcaboz** [comment]
Corresponds to "On Hand"
