### ISSUE TITLE
Selection of vendor (farmer) localtion differs between warehouses

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#34]
The selection of the source Location (farmer vendor location) and the destination location (Stock of the given warehouse) seems to differ depending on the warehouse chosen. With warehouse "Carrière" or "Gueybli" selected odoo does not behave as expected and does not display the correct source location (farmer vendor location).

It works as expected when choosing the "Kessel" warehouse:
<img width="1440" alt="Bildschirmfoto 2021-09-26 um 11 11 42" src="https://user-images.githubusercontent.com/90847414/134801913-878f6a64-b6fb-4573-b0af-148aee652ca0.png">
<img width="1440" alt="Bildschirmfoto 2021-09-26 um 11 11 58" src="https://user-images.githubusercontent.com/90847414/134801917-acbf29f1-6f00-4619-9fb7-e59831a30459.png">
<img width="1440" alt="Bildschirmfoto 2021-09-26 um 11 12 49" src="https://user-images.githubusercontent.com/90847414/134801923-1fd50ab3-e030-434f-9d23-45797832ac60.png">
<img width="1440" alt="Bildschirmfoto 2021-09-26 um 11 13 48" src="https://user-images.githubusercontent.com/90847414/134801927-888203fb-96af-4137-9869-465a3d3514df.png">

When choosing the "Carrière" Warehouse the line where to select the source location looks different. Even when choosing the farmer vendor location it won't appear in the traceability report. Instead it just shows the generec vendor location. 
<img width="1440" alt="Bildschirmfoto 2021-09-26 um 11 15 22" src="https://user-images.githubusercontent.com/90847414/134802055-c13c9b30-c438-4349-b344-7768d0ab60b5.png">

Compare this line with the same step when the "Kessel" warehouse is selected.
<img width="1440" alt="Bildschirmfoto 2021-09-26 um 11 16 27" src="https://user-images.githubusercontent.com/90847414/134802060-1c93e623-f6eb-4a9a-bc56-e3b5bd8c5251.png">
<img width="1440" alt="Bildschirmfoto 2021-09-26 um 11 17 12" src="https://user-images.githubusercontent.com/90847414/134802085-58ed7c93-ce42-498f-80f6-057512694b76.png">

The vendor location of KES/021 is not shwon here.
<img width="1440" alt="Bildschirmfoto 2021-09-26 um 11 18 05" src="https://user-images.githubusercontent.com/90847414/134802098-b3865bc8-0e93-47b5-9451-a3fb4a0bc1f4.png">

The same issues when choosing the "Gueybli" warehouse. Additionaly also the destination location is wrong (Vendor location instead of GUE/Stock.
<img width="1440" alt="Bildschirmfoto 2021-09-26 um 11 21 49" src="https://user-images.githubusercontent.com/90847414/134802207-b16f3d24-12c9-480e-91dc-da8f35e6e4a1.png">
<img width="1440" alt="Bildschirmfoto 2021-09-26 um 11 23 33" src="https://user-images.githubusercontent.com/90847414/134802217-24f18720-0614-4b45-baf1-242bfcd1b135.png">

As a result, there is no stock in GUE/Stock.
<img width="1440" alt="Bildschirmfoto 2021-09-26 um 11 41 15" src="https://user-images.githubusercontent.com/90847414/134802501-a8a3c9e1-ec98-42c7-b537-949ff3940237.png">

**Comment by treviser** [comment]
This is defined in the Inventory/Configuration/Operation Types:
The checkbox "Show Detailed Operations" must be ticked:

![image](https://user-images.githubusercontent.com/1814941/134802600-49ad3d47-587b-44c4-a69c-4a5c8bfa9210.png)

**Comment by treviser** [comment]
Should work now, please check and close, if working correctly.

**Comment by dastcaboz** [comment]
Works as expected now. Thank you Trevi! Greetings from Paris Charle de Gaule.

**Comment by treviser** [comment]
Gute Reise!
