### ISSUE TITLE
Life version: Add Current Stock smart button in Partner view

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#41]
In the life version, the smart button showing the current stock is missing I think. Please add as in the test version.
<img width="1440" alt="smart_button_stock" src="https://user-images.githubusercontent.com/90847414/137476450-2c2e60ad-c902-4f0a-8940-b8b48c8bf4fa.png">

**Comment by treviser** [comment]
@candidroot See https://github.com/twanda/vertical-agriculture/issues/45

**Comment by candidroot** [comment]
@treviser 
Now you can check on the "caboz2.twanda-hosting.ch"  live server,
I already upgrade module on live server
is there any update please let me know,
thanks

**Comment by treviser** [comment]
@dastcaboz Can you please check without polluting the production database?

**Comment by dastcaboz** [comment]
The button is there in life version
[issue # 41.pdf](https://github.com/twanda/vertical-agriculture/files/7452587/issue.41.pdf)

**Comment by dastcaboz** [comment]
A detail: Can the Current Stock get displayed with a separator for thousands but no decimal places. Thank you
