### ISSUE TITLE
Layout of Invoices, etc. are not correct

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#43]
The a layout chosen for invoices or other forms is not correctly generated. Probably a problem with css styling.
[Quotation-SO070.pdf](https://github.com/twanda/vertical-agriculture/files/7353184/Quotation-SO070.pdf)

**Comment by treviser** [comment]
@dastcaboz I think it works now, please check and close if correct.
[Delivery Slip -  - KES_PICK_00012.pdf](https://github.com/twanda/vertical-agriculture/files/7359001/Delivery.Slip.-.-.KES_PICK_00012.pdf)
