### ISSUE TITLE
Weight correction creates backorder

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#44]
A weight correction automatically creates a backorder of the weigght difference. This can be deleted. But it would be better if odoo would not create a backorder at all.
<img width="1440" alt="backorder_from_weight-correction_02" src="https://user-images.githubusercontent.com/90847414/137491661-1597a1a3-e7d5-4e6e-9fec-ce94326c8ba3.png">
<img width="1440" alt="backorder_from_weight-correction" src="https://user-images.githubusercontent.com/90847414/137491651-54a28fcb-f052-44b7-87ce-c63b3cfb7e4a.png">

**Comment by treviser** [comment]
@dastcaboz I think it works now, please check.

[Delivery Slip -  - KES_PICK_00012.pdf](https://github.com/twanda/vertical-agriculture/files/7358997/Delivery.Slip.-.-.KES_PICK_00012.pdf)

**Comment by treviser** [comment]
@dastcaboz 
This is by design for incoming weight corrections. If there is already a backorder existing, the existing backorder will be adapted. If there is no backorder created yet, a new one must be created in order to ensure the proper fulfillment of the purchase order by the purchasing agent.

**Comment by dastcaboz** [comment]
OK. We will have to see how this works in reality. Usually we do not create a backorder for small quantities as it does not make much sense to move a truck to pick small quantities. We rather take this into account when refinancing the purchaising agent the next time.

Cant't we have the same pop-up that lets us decide wether we want to create a backorder or not (instead of creating an automatic backorder)?

**Comment by treviser** [comment]
@dastcaboz 
It is not the meaning of a backorder (which creates a new partial receipt transfer operation) to be fullfilled by a separate incoming delivery, but that it is accounted for when the next regular delivery arrives. The backorder will stay in state "ready" as long as it is not fullfilled by the incoming quantities. It is at the discretion of Caboz to cancel such "open" backorders and to "close" the originating purchase order by creating a bill. In this case the received and billed quantity will be lower than the originally demanded quantity.
