### ISSUE TITLE
Caboz2.twanda-hosting.ch : Unable to update vertical-agriculture modules, model agri.plantation

### ISSUE THREAD

**Issue by treviser** [twanda/vertical-agriculture#45]
@candidroot 

I forgot how we fixed that last time, but we have the same issue again on cabo2.twanda-hosting.ch which is the supposed to be the production database.
Credentials are the same as for test-caboz.twanda-hosting.ch, see my Skype message also.

**Comment by candidroot** [comment]
@treviser 
Hello, Already upgrade module on "cabo2.twanda-hosting.ch" server please check it,
is there any issue then please let me know,
thanks

**Comment by treviser** [comment]
@candidroot thanks, what was the reason?

**Comment by candidroot** [comment]
@treviser 
In the live server some packages not installed,
thats why its give error,

**Comment by treviser** [comment]
@candidroot which ones?

**Comment by candidroot** [comment]
@treviser 
its python package name is "area"

**Comment by treviser** [comment]
@candidroot I also did install the package on both servers, I have pulled the latest code on both servers, I have restarted the Odoo server, I have updated the apps list in Odoo and updated our modules. On production (caboz2) everything went smoothly, but on test-caboz I have the same error again when trying to update the agri module. Why is this so shakey? Please advise.

**Comment by candidroot** [comment]
@treviser 
You can see in attach file you missing to install one library,
So i installed in test server and also upgrade module,
now you can check it and let me know is there any update on this,
thanks

![image_2021_11_02T06_07_21_102Z](https://user-images.githubusercontent.com/39722234/139795152-166b1e08-3e13-4420-9575-b534ab64bf5c.png)

**Comment by treviser** [comment]
It works now, thanks.
