### ISSUE TITLE
Current stock Smart button does not show the correct weight

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#48]
The customized smart button that shows the stock of each vendor does not show the weight per vendor, but the total volume purchased. It should only show the stock of the vendor selected.

**The figure representing the stock should have a separator for thousands and no dezimals!**

The smart button in these two vendors views show the same stock.
 
![issue](https://user-images.githubusercontent.com/90847414/140327268-eaee3400-ad14-4cc8-b470-5653d7e2946d.jpg)

![issue 2](https://user-images.githubusercontent.com/90847414/140327531-e8f78211-ade7-430f-ad88-6a63a5a99bcc.jpg)

**Comment by dastcaboz** [comment]
Maybe this is only an issue with the pisteurs.

**Comment by candidroot** [comment]
@treviser 
I committed code so please take pull and restart server and upgrade module,

The customized smart button that shows the stock of each vendor does not show the weight per vendor, but the total volume purchased. It should only show the stock of the vendor selected
       For this you need to check in partner must have different vendor location, we show current stock base on partner 
       vendor location,
       Please check attached screenshot,


The figure representing the stock should have a separator for thousands and no dezimals!
    For this issue its has been fixed so please you can check it after  take latest pull and upgrade module 

![screenshot-localhost_8069-2021 11 09-12_27_28](https://user-images.githubusercontent.com/39722234/140876772-23c7c284-8453-46bf-acb1-72f051efe0d2.png)

**Comment by treviser** [comment]
@dastcaboz please check.

**Comment by treviser** [comment]
@dastcaboz the stock smart button can only work for vendors, which have a dedicated stock location assigned. In our design, this is only valid for farmers, but not for purchasing agents or any other kind of vendors.
