### ISSUE TITLE
Important!!! Unabel to receive more than initially demanded

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#49]
When creating a incoming delivery (Vendor Location to Stock) odoo blocks the process when more is delivered than originally demanded in the Purchase Order.

The same warning appears, if a through a "Weight Correction" the delivered weight is higher than the ordered weight on the Purchase Order.

Plaese fix this bug quickly as this is a frequent situation.

![issue 3](https://user-images.githubusercontent.com/90847414/140331871-5758cc5e-c074-494f-ad6b-9ad6f280d08d.jpg)

**Comment by dastcaboz** [comment]
This is the warning if the "Weight Correction" results in a weight that exceeds the originally ordered quantity.
![issue 4](https://user-images.githubusercontent.com/90847414/140334063-1267e5aa-7411-41a2-bb07-0ca2e9dbf664.jpg)

**Comment by candidroot** [comment]
@treviser 
I committed latest code,
Please take latest pull and restart server then check it,
Is there any update on this please let me know,
thanks

**Comment by treviser** [comment]
Updated test and prod server and restarted Odoo.

@dastcaboz Please check.

**Comment by treviser** [comment]
@candidroot Was this a original Odoo design flaw?

**Comment by candidroot** [comment]
@treviser 
No it's our custom code related issue,
