### ISSUE TITLE
„City“ in Partner as a related field

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#52]
To insure data consistency it would be desirable to change the field „City“ in the partner form into a related table of city name to choose from. Just like the „state“ field. Is this possible?

**Comment by candidroot** [comment]
@treviser i have created new module called "base_city_extend". this module have new field(M2o, city_id) and also updated existing city to this new field. you have to install this module(base_city_extend).

**Comment by dastcaboz** [comment]
@siddharth7815 : could you please install this module on the test and production server? Thannk you.

**Comment by candidroot** [comment]
@dastcaboz ....please test on test server.

**Comment by dastcaboz** [comment]
@siddharth7815 … Works fine! Please upload it on production server caboz2.twanda-hosting.ch
