### ISSUE TITLE
Upload new farmer list on productive server

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#53]
Hi Siddhardt, we need to delete the farmers already uploaded on the prodction server caboz2.twanda-hosting.ch. I tried it myselef but incountered the following issues:

1. Unable to delete more than one farmer at once.
2. Unable to upload the new farmer list

**Unable to delete more than one farmer:**
https://user-images.githubusercontent.com/90847414/148069933-a9b16029-cf1a-4045-b1f0-9c74ee8abece.mov

**Unable to upload new farmer list:**
<img width="2557" alt="Bildschirmfoto 2022-01-04 um 10 21 03" src="https://user-images.githubusercontent.com/90847414/148070371-f1d62150-eedd-45a4-a9d0-16ceb16e962a.png">

**Please upload this list:**
[211209_farmers_Annexe_13_nouveau_registre_import_odoo.xlsx](https://github.com/twanda/vertical-agriculture/files/7808108/211209_farmers_Annexe_13_nouveau_registre_import_odoo.xlsx)

Please analyse the problem and if possible make sure, we can delete and upload farmers and in the near future plantations ourself without incountering issues.

**Comment by dastcaboz** [comment]
Hi Siddharth, please resolve this issue within due time. As Trevi ist still in hospital, please go ahead without his implication. 

To do:

1. Delete all existing farmers on the productive server caboz2.twanda-hosting.ch
2. Upload the new farmers with attached excel list

Let me know directly if you have questions. 
Thank you for a timely response and best regards, Daniel
[211209_farmers_Annexe_13_nouveau_registre_import_odoo.xlsx](https://github.com/twanda/vertical-agriculture/files/7820479/211209_farmers_Annexe_13_nouveau_registre_import_odoo.xlsx)

**Comment by dastcaboz** [comment]
Hello Siddharth, it is very important that we resolve with this issue fast. Let me know wether you work on it or if you need additional information. As Trevi is still in hospital: can we have a call to see how we collaborate in the meantime?

Best, Daniel

**Comment by dastcaboz** [comment]
@siddharth7815: please react on above messages, as this is an urgent matter! Thank you, Daniel

**Comment by candidroot** [comment]
@dastcaboz i do not have production server access. let's have quick call to do this.

**Comment by candidroot** [comment]
@dastcaboz 

1) Unable to delete more than one farmer at once. ==> this has been solved. but you cah not delete farmer because depedent data of invoice,sale.
2) Unable to upload the new farmer list. ==> please make sure you are importing name value for partner as it is required.

**Comment by dastcaboz** [comment]
> @dastcaboz i do not have production server access. let's have quick call to do this.

@siddharth7815: I am about to get admin access info of the productive server.

**Comment by dastcaboz** [comment]
@siddharth7815 : How can I reach you. I am on Skype: caboz.daniel.staehli

**Comment by dastcaboz** [comment]
> 1. Unable to delete more than one farmer at once. ==> this has been solved. but you cah not delete farmer because depedent data of invoice,sale.

@siddharth7815: On the production server still impossible to delete more than one farmer at once. There are no dependencies on invoices or sales because there are no sales and purchases registered yet.

**Comment by dastcaboz** [comment]
> 2\. Unable to upload the new farmer list. ==> please make sure you are importing name value for partner as it is required.

@siddharth7815 : what is the name value?

**Comment by candidroot** [comment]
@dastcaboz Issue has been solved
