### ISSUE TITLE
Productive server: Doubled vendor locations

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#56]
@siddharth7815 very urgent:

We started to register purchases on the productive server. 

When registering the farmer lots, their vendor location appears twice. Probably a bug in relation to the deleting of the farmer list and upload the new farmer list.

Please resolve this urgently. If this is related with a fundamental bug when updating the farmer list, please resolve this bug.

Thank you, Daniel

**Comment by dastcaboz** [comment]
![double vendor location](https://user-images.githubusercontent.com/90847414/149928617-0267e539-d2cb-41f8-a8ef-4640e2b28df1.jpg)

**Comment by dastcaboz** [comment]
Issue is partially resolved. Doubled internal vendor locations are deleted.

**Comment by dastcaboz** [comment]
@siddharth7815 : Please make sure, that when deleting a farmer, also the related vendor location is automatically deleted or at least archived.

**Comment by candidroot** [comment]
@dastcaboz ...please test on test server.

**Comment by dastcaboz** [comment]
Works fine. Thank you.
