### ISSUE TITLE
Change field "Plantation Code" to a incremential field

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#57]
Detach the field "plantation code" from "plantation name". "Plantation Name" can remain an editable field. 

"Plantation code" should be changed into an unique, automatically generated name.

The naming system should be structured as follows: KES/P00001

"KES": Abbreviation for the Section (see issue 57)

"P": Plantation

"00001": ascending numerical sequence

**Comment by candidroot** [comment]
@dastcaboz ...please have a look on test server.

**Comment by dastcaboz** [comment]
Great, Thank you.
