### ISSUE TITLE
Add new field "Section" to Farmer and Plantation

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#58]
Create a new field in Farmer and Plantation called "Section". We should be able to generate new sections and to chosse from a list. A farmer or a plantation can be part of one section only.

When creating a new section an abbreviation for the section defined. 

Example:

Currently we have three sections (abbreviation in parentheses):

1. Kessel (KES)
2. Carrière (CAR)
3. Duekoue (DKG)

**Comment by candidroot** [comment]
@dastcaboz ...please have a look on test server.

**Comment by dastcaboz** [comment]
Great. Thank you
