### ISSUE TITLE
Create new field in plantation "Type"

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#59]
Create a new field in plantation called "Type". 

We should be able to specify a plantation and choose from a list we can edit ourself and add new types of plantations.

Example:

Plantation 1, Type: Plantation
Plantation 2, Type: Sump
Plantation 3. Type: Fallow land
etc.

**Comment by candidroot** [comment]
@dastcaboz ...please have a look on test server

https://user-images.githubusercontent.com/39722234/153205281-a38c6fc2-37b5-4637-b888-f9de82197b37.mp4

**Comment by dastcaboz** [comment]
@siddharth7815 … Looks great. Thank you

But we have to extend the data model.

A **farmer** can own one or several **plantations**. A plantation consists of one or several **plots**.

![Page6](https://user-images.githubusercontent.com/90847414/153592191-c24de26b-408d-4025-8a0e-e98be6bb3831.jpg)

What is now a PLANTATION will become a PLOT. Between FARMER and the Plot we need the entity PLANTATION that consists of one to several PLOTS.

Let me know if something is not clear.
