### ISSUE TITLE
incoming_lot_enhancements

### ISSUE THREAD

**Issue by treviser** [twanda/vertical-agriculture#6]
When editing the first (prepopulated) line of the detailed operation tab, there is no lot number created, only when adding a new line, the number is created.
![2021-03-25_08-43](https://user-images.githubusercontent.com/1814941/112437351-23568800-8d47-11eb-90ae-059af15b211a.png)

**Comment by candidroot** [comment]
@treviser issue solved !

**Comment by treviser** [comment]
Thanks.

Tested on 20210328, ok
