### ISSUE TITLE
Agriculture Module: Geometry based on GPX files is only defined on „Plot“ not on "Farm". 

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#64]
<img width="1394" alt="220906_issue_01" src="https://user-images.githubusercontent.com/90847414/188828914-1e34f4b1-58b0-44d3-8519-a3b7accece78.png">

„Farm“: Geometry based on gpx-files is only defined on „Plot“ not in "Farm".

**Comment by candidroot** [comment]
Import GPX has been removed from farm level as per your comment .
