### ISSUE TITLE
Agriculture Modul: View of "Plot" geometries in „Farm“ 

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#65]
<img width="1394" alt="220906_issue_02" src="https://user-images.githubusercontent.com/90847414/188829332-f9b39d81-2947-4daa-bb49-84cfc332c65e.png">

„Farm“: Geometries in „Farm“ must be a view of all geometries related to the „Farm“. 

For future development, it would be good if we can identify differnt types of plots with different colors, and filter them in the geometry view by type.

**Comment by lulu-maker** [comment]
@dastcaboz could you provide GPX files for plot to display all plots related polygone on farm level.

**Comment by dastcaboz** [comment]
Hi Siddharth and team,

As discussed some polygones attached.

Best regards,

Daniel




CABOZ AG
Hermetschloostrasse 70
CH-8048 Zürich
Switzerland

Daniel Stähli
***@***.*** ***@***.***>
Phone: +41 76 280 31 57

www.caboz.ch <http://www.caboz.ch/>

**Comment by dastcaboz** [comment]
[Archiv.zip](https://github.com/twanda/vertical-agriculture/files/9548337/Archiv.zip)

**Comment by candidroot** [comment]
Geometries in Farm will show view of all geometries related to the plots has been updated on server.
