### ISSUE TITLE
Agriculture Modul: Choosing farmer and date directly in the form of "Farm"

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#66]
<img width="1394" alt="220906_issue_03" src="https://user-images.githubusercontent.com/90847414/188830105-686fe629-397d-47ec-8cd5-723553212640.png">

„Farm“: Button on top is not really needed. But it should be possible to change the farmer directly in the form together with the field „Farming since“. Entering the date must be compulsory to save the dataset.

**Comment by candidroot** [comment]
@dastcaboz Change Farmer wizard has been removed.Now you can change farmer from details tab.
