### ISSUE TITLE
Agriculture Modul: „Area" is only calculated in „Plot“ not in "Farm"

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#67]
<img width="1394" alt="220906_issue_04" src="https://user-images.githubusercontent.com/90847414/188830601-829c2b33-e616-4d7b-a7e3-4d1af5e0d96b.png">

„Farm“: „Area" is only calculated in „Plot“ to which the gpx File is related to. 
Instead we can show here the toatl of all plots related to a plot filtered by type, with information like number of plots, total size in ha:

Example:

<img width="444" alt="Bildschirmfoto 2022-09-07 um 10 37 58" src="https://user-images.githubusercontent.com/90847414/188832091-5fbc06b3-cd89-482a-a89b-23840bb284d3.png">

**Comment by candidroot** [comment]
@dastcaboz  Area fields has been removed from farm level.

**Comment by dastcaboz** [comment]
This view would probably better placed in the "Plots" tap.

![grafik](https://user-images.githubusercontent.com/90847414/189329046-376cf343-7f0c-4e06-a1f7-06f8d3dc9259.png)

**Comment by candidroot** [comment]
List view of plot in Farm view has been changes according to discussion in meeting.
