### ISSUE TITLE
Agriculture Modul: Lists view of related "Plots" in „Farm“

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#68]
<img width="1394" alt="220906_issue_05" src="https://user-images.githubusercontent.com/90847414/188832365-e7b3fc7f-d262-4cec-ab74-c6ca290bd5a0.png">

„Farm“: Adapt the lists of Plots related to the „Farm“ (see screenshot)

**Comment by candidroot** [comment]
@dastcaboz  Change the list view according to your comment except code as it has been removed for avoiding duplication of name and code field.
