### ISSUE TITLE
Agriculture Modul: Several issues in "Farm"

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#69]
<img width="1394" alt="220906_issue_06" src="https://user-images.githubusercontent.com/90847414/188833312-edb3c528-096e-4bc4-b35d-88f9e1d5fc5b.png">

„Farm“:

1. „Owner“: delete the field „Owner“, because a farm has no related „Owner“ (just a related „Farmer“)
2. List of related „Plots“: We must have a field with the „Name“ (internal UNIQUE Code) as Dropdown, showing all „Plots“ not yet related to a „Farm“. 
3. see other comments on screenshot
4. The "Name" field must be unique, as we use here the internal Code of a Plot.

**Comment by siddharth7815** [comment]
@dastcaboz issue has been resolved. please have a look.
