### ISSUE TITLE
Agriculture Modul: "Code" and "Name" in "Farm" and "Plot"

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#71]
<img width="1394" alt="220906_issue_08" src="https://user-images.githubusercontent.com/90847414/188834952-2a7c5151-17a6-47e7-ac1a-8b45ec00b21d.png">

For "Plot" and "Farm" the field "Name" should be UNIQUE. We use here a internal Code. In all references to "Plot" or "Farm" we should be able to search for this internal Code rather than the code automatically generated by odoo. The field "Code" can stay but should not be editable for non-authorized users.

**Comment by candidroot** [comment]
@dastcaboz Removed Street2 and removed code from Plots. Applied constraint for unique name of the plot.

**Comment by dastcaboz** [comment]
"Name" is still not unique. 
If not yet existing: please add a unique ID and display it as a non-editabel field (where "Code" was).
![220909_issue_14](https://user-images.githubusercontent.com/90847414/189333567-a52a27b5-2827-4e94-abb9-02304a275cfc.jpg)

**Comment by siddharth7815** [comment]
For Plot name unique, constraint applied on the test server.
