### ISSUE TITLE
Agriculture Modul: List view of history records of "Plot" and "Farm"

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#72]
<img width="1394" alt="220906_issue_09" src="https://user-images.githubusercontent.com/90847414/188836215-879ebfc5-18b8-4b90-8c3b-000f77d42f6e.png">

In the list view of the history records of a "Plot" or "Farm" we mainly need the "Valid from" and "Valid until" dates. You can also add "Name" and "Farmer".

**Comment by siddharth7815** [comment]
Changes in list view of the history records has been updated on test server. Please check.
