### ISSUE TITLE
Agriculture Modul: Code and Name for "Plot" and "Farm"

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#73]
<img width="1394" alt="220906_issue_10" src="https://user-images.githubusercontent.com/90847414/188837186-b1603935-20a9-48c9-8236-d15f71f9ab59.png">

In "Plot" and "Farm" the "Name" must be unique. The field "Code" should not be editable and autmatically generated by odoo.

**Comment by candidroot** [comment]
@dastcaboz Removed Farm code. Farm name will be unique issue has been fixed.
