### ISSUE TITLE
  Agriculture Modul: Selection of a "Farm" in "Plot"

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#74]
<img width="1394" alt="220906_issue_11" src="https://user-images.githubusercontent.com/90847414/188837537-de8ccb04-2a03-4d2e-9396-39d72c66ac8b.png">

To make the selection of a farm more user-friendly, it would be good if 

1. we first can select the farmer by name or code. 
2. select then in a new field from the farms related to this farmer (only these farms are displayed for selection)

**Comment by candidroot** [comment]
@dastcaboz  Change the position of Farm and Farmer. So now, user can select Farmer first and based on that Farm of that specific farmer will be shown in dropdown.
