### ISSUE TITLE
Odoo refuses to create Plot and Farm because of Name

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#79]
Unabel to register a new "Plot" or "Farm" because of unique field "Name". Message appears with any name and although there is no other "Farm" or "Plot" yet defined.

<img width="1357" alt="farm_name_unique" src="https://user-images.githubusercontent.com/90847414/191738468-aa07993c-8a70-4c7d-b389-f9d20603e109.png">
<img width="1357" alt="plot_name_unique" src="https://user-images.githubusercontent.com/90847414/191738473-b30576f0-70a4-477e-84ae-e456d697c49c.png">

**Comment by siddharth7815** [comment]
Issue has been fixed on test server. Please check .
